arb-dir: lib/src/core/locale/arbs # Директория, в которой хранятся файлы переводов
output-dir: lib/src/core/locale/gen # Директория, в которой находится сгенерированный файл локализации
template-arb-file: app_en.arb # Файл-шаблон, где описываются параметры строк
output-localization-file: app_localizations.dart # Сгенерированный файл локализации
nullable-getter: false # В методе of(context) можно не делать проверку на null
