const String kAppName = 'Wumbi';
const String kSupportUrl = 'mailto:support@wumbi.app';

/// Public pages on wumbi.app, opened with `url_launcher` in an external browser.
/// Generated by `wumbi_landing/site-pages.mjs`; keep the paths in sync with the
/// `STATIC_PAGES` list there, and with `TEMPLATE_PAGE.path` in `seo.config.mjs`.
const String kWebsiteUrl = 'https://wumbi.app/';
const String kAboutUrl = 'https://wumbi.app/about/';
const String kPrivacyUrl = 'https://wumbi.app/privacy/';
const String kTermsUrl = 'https://wumbi.app/terms/';
const String kPressUrl = 'https://wumbi.app/press/';

const double kPageHorzPadding = 16;

/// Wider gutter for list blocks (dashboard wallets, wallet details rows).
const double kListHorzPadding = 24;

/// Extra inset applied to the numpad on top of [kPageHorzPadding].
const double kNumpadHorzPadding = 28;

/// Transaction screen limits (spec 8.5).
const int kMaxIntegerDigits = 12;
const int kMaxDescriptionLength = 80;
const int kMaxTagsPerTransaction = 10;
const int kMaxTagLength = 30;
const int kMaxWalletNameLength = 40;
const int kTransactionsPageSize = 50;

/// Hero tags shared between pages.
const String kHeroFab = 'hero-fab-transaction';
String heroWalletName(String walletId) => 'hero-wallet-name-$walletId';
String heroWalletBalance(String walletId) => 'hero-wallet-balance-$walletId';
