import 'package:collection/collection.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

import '../../../core/fx/fx_service.dart';
import '../../../core/money/amount_input.dart';
import '../../../core/money/currency_type.dart';
import '../../../core/money/money.dart';
import '../../../core/utils/enums/repeat_frequency.dart';
import '../../../core/utils/enums/transaction_status.dart';
import '../../../core/utils/enums/transaction_type.dart';
import '../../../core/utils/extensions/date_time_extensions.dart';
import '../../wallet/data/models/wallet_model.dart';
import '../data/models/transaction_model.dart';

part 'transaction_state.freezed.dart';

enum TransactionMode { create, edit }

enum RateStatus { none, loading, ok, stale, error }

/// Route arguments: `walletId` (preselect) and/or `transactionId` (edit mode).
class TransactionArgs {
  const TransactionArgs({this.walletId, this.transactionId});

  final String? walletId;
  final String? transactionId;

  bool get isEdit => transactionId != null;

  @override
  bool operator ==(Object other) =>
      other is TransactionArgs && other.walletId == walletId && other.transactionId == transactionId;

  @override
  int get hashCode => Object.hash(walletId, transactionId);
}

/// Read-only counterpart line in transfer edit mode ("→ Checking +$50.00").
@freezed
abstract class TransferCounterpart with _$TransferCounterpart {
  const factory TransferCounterpart({
    required String walletName,
    required Money amount,

    /// True when the viewed wallet is the source (money goes *to* the counterpart).
    required bool outgoing,
  }) = _TransferCounterpart;
}

@freezed
abstract class TransactionState with _$TransactionState {
  const TransactionState._();

  const factory TransactionState({
    @Default(TransactionMode.create) TransactionMode mode,
    @Default(false) bool isLoading,

    /// Type shown in edit mode. Income ↔ expense can be switched; transfer is fixed.
    TransactionType? editingType,
    TransactionModel? existing,
    TransferCounterpart? counterpart,

    /// Target wallet (D3). Null only when there are no wallets at all.
    WalletSummary? wallet,
    @Default([]) List<WalletSummary> wallets,
    required CurrencyType entryCurrency,
    @Default('') String amountInput,
    FxRate? rate,
    @Default(RateStatus.none) RateStatus rateStatus,
    @Default('') String description,
    @Default([]) List<String> tags,

    /// Chosen day (date part only); time is resolved on save (spec 11.2).
    required DateTime date,
    @Default(RepeatFrequency.never) RepeatFrequency repeat,

    /// Generated by a rule → chip is read-only.
    @Default(false) bool repeatLocked,
    @Default(false) bool isSaving,
    String? validationError,

    /// Edit mode: the prefilled amount has not been touched yet — the first
    /// digit typed replaces it instead of appending.
    @Default(false) bool amountPristine,

    /// Edit mode baseline (for [isDirty]).
    @Default('') String initialAmountInput,
    @Default([]) List<String> initialTags,
  }) = _TransactionState;

  bool get isEdit => mode == TransactionMode.edit;
  bool get isTransferEdit => isEdit && editingType == TransactionType.transfer;
  bool get sameCurrency => wallet != null && entryCurrency == wallet!.currency;

  /// The chosen day is after today → saving stores the row as *upcoming*
  /// (not counted until `UpcomingPoster` promotes it). Mirrors the rule the
  /// repository applies on `create` / `update`.
  bool get willBeUpcoming => TransactionStatus.forDate(date).isUpcoming;

  /// Edit mode: the loaded transaction is still upcoming (not counted yet).
  bool get isExistingUpcoming => existing?.isUpcoming ?? false;

  /// Parsed `amountInput` in the entry currency (null when empty / zero).
  Money? get entryMoney => AmountInput.toMoney(amountInput, entryCurrency);

  /// Converted into the wallet currency (equals [entryMoney] when same currency).
  Money? get walletMoney {
    final entry = entryMoney;
    final w = wallet;
    if (entry == null || w == null) return null;
    if (entry.currency == w.currency) return entry;
    final r = rate;
    if (r == null) return null;
    return convertMoney(entry, w.currency, r.rate);
  }

  /// Edit mode: anything differs from the loaded transaction.
  bool get isDirty {
    final e = existing;
    if (!isEdit || e == null) return false;
    return amountInput != initialAmountInput ||
        description.trim() != e.description ||
        !const ListEquality<String>().equals(tags, initialTags) ||
        date != e.transactionDate.onlyDate() ||
        (editingType != null && editingType != e.type);
  }

  bool get rateReady => sameCurrency || (rate != null && rateStatus != RateStatus.error);

  bool get canCommit {
    final m = walletMoney;
    return m != null && m.minor > 0 && rateReady && !isSaving && !isLoading;
  }

  /// Amount typed in a foreign currency, recorded alongside the converted one (D2).
  Money? get originalForStorage => sameCurrency ? null : entryMoney;

  double? get rateForStorage => sameCurrency ? null : rate?.rate;
}
